# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: ggalancs.HFL
PackageVersion: 0.21.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Commands:
  - hfl
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ggalancs/hfl/releases/download/v0.21.0/hfl-0.21.0.msi
    InstallerSha256: 28D39F95CBF685AC9516C583410BB638507F4FA8FDA73A19CF4270D88A4A7EB2
    AppsAndFeaturesEntries:
      - UpgradeCode: '{F9FDE6C0-1D4C-4B7B-8C18-5AEA57F3A5C1}'
ManifestType: installer
ManifestVersion: 1.9.0
